const STATUS_CODES = {
    SUCCESS: '200',
    NO_DATA_FOUND: '404',
    WARN_REQUEST: '422',
    BAD_REQUEST: '400',
    INTERNAL_SERVER: '500',
    UNAUTHORIZED: '401',
    FORBIDDEN: '403',
};

export { STATUS_CODES };
